homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 37
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant

frontend:

http:
  ip_ban_enabled: True
  login_attempts_threshold: 5

discovery:
  ignore:
    - netgear_router

conversation:
history:
logbook:
config:
sun:
updater:
recorder:

system_health:
device_tracker:
  - platform: netgear
    host: !secret netgear_host
    username: !secret netgear_user
    password: !secret netgear_password
    port: !secret netgear_port
    interval_seconds: 30
    consider_home: 60
    new_device_defaults:
      track_new_devices: False

ifttt:
  key: !secret ifttt_key

binary_sensor:
  - platform: rest
    resource: http://localhost:5000/api/calendarStatus
    method: GET
    name: David Meeting
    device_class: occupancy
    value_template: '{{ value_json.state.open }}'

cast:
  media_player:
  - host: 192.168.15.205
  - host: 192.168.15.207
  - host: 192.168.15.212

sensor:
  - platform: darksky
    api_key: !secret dark_sky_key
    monitored_conditions:
      - summary
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - wind_speed
      - humidity
      - cloud_cover
      - precip_probability
  - platform: pi_hole
    host: 192.168.15.202
    monitored_conditions:
      - ads_percentage_today
      - dns_queries_today
  - platform: template
    sensors:
      david_meeting_status:
        value_template: '{% if is_state("binary_sensor.david_meeting", "on") %}In Meeting{% else %}Free{% endif %}'
        friendly_name: David Status
        icon_template: >-
          {% if is_state('binary_sensor.david_meeting', 'on') %}
            mdi:phone-in-talk
          {% else %}
            mdi:phone-hangup
          {% endif %}
      printer_status:
        value_template: "{% if states.device_tracker.canone3a1e9 %}
        {% if is_state('device_tracker.canone3a1e9', 'home') %}
          Online
        {% else %}
          Offline
        {% endif %}
        {% else %}
          Unknown
        {% endif %}"
        friendly_name: Printer
      circle_status:
        value_template: "{% if states.device_tracker.circle %}
        {% if is_state('device_tracker.circle', 'home') %}
          Online
        {% else %}
          Offline
        {% endif %}
        {% else %}
          Unknown
        {% endif %}"
        friendly_name: Circle
      pollen_rating_today:
        value_template: "{{ states.sensor.allergy_index_today.attributes.rating}}"
        friendly_name: Pollen Level Today
      pollen_today_source:
        value_template: "{{ states.sensor.allergy_index_today.attributes.allergen_name_1}}"
        friendly_name: Pollen Primary Source
      garage_door_status:
        friendly_name: 'State of the door'
        value_template: '{{ states.cover.garage_door.state }}'
      garage_door_time_in_state:
        friendly_name: 'Since'
        value_template: '{{ states.cover.garage_door.attributes.time_in_state }}'
      garage_door_wifi_signal_strength:
        friendly_name: 'WiFi strength'
        value_template: '{{ states.cover.garage_door.attributes.wifi_signal_strength }}'
        unit_of_measurement: 'dB'

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
  - platform: airvisual
    api_key: !secret airvisual_api_key
    monitored_conditions:
      - us
  - platform: pollen
    zip_code: !secret zip_code
    monitored_conditions:
     - allergy_index_today
     - allergy_index_tomorrow
  - platform: rest
    name: SpaceX
    json_attributes:
     - mission_name
     - launch_site
     - rocket
    value_template: '{{ value_json["launch_date_unix"] }}'
    resource: 'https://api.spacexdata.com/v2/launches/next'
  - platform: template
    sensors:
      spacex_next_launch_day:
        friendly_name: 'Launch Date'
        value_template: '{{ states.sensor.spacex.state | int | timestamp_custom("%m/%d/%Y")}}'
      spacex_next_launch_time:
        friendly_name: 'Launch Time'
        value_template: '{{ states.sensor.spacex.state | int | timestamp_custom("%H:%M")}}'
        unit_of_measurement: 'h'
      spacex_next_rocket:
        friendly_name: 'Rocket Name'
        value_template: '{{ states.sensor.spacex.attributes["rocket"]["rocket_name"] }}'
      spacex_next_launch_site:
        friendly_name: 'Launch Site'
        value_template: '{{ states.sensor.spacex.attributes["launch_site"]["site_name_long"] }}'
      spacex_next_mission_name:
        friendly_name: 'Mission Name'
        value_template: '{{ states.sensor.spacex.attributes["mission_name"] }}'

cover:
  - platform: garadget
    covers:
      47004d001151353432393433:
        username: !secret garadget_username
        password: !secret garadget_password
        name: Garage Door

telegram_bot:
  platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chat_id

notify:
 - name: halladay_bot
   platform: telegram
   chat_id: !secret telegram_chat_id

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password

wemo:
  static:
    - 192.168.15.155
    - 192.168.15.156

tplink:
  discovery: false
  switch:
    - host: 192.168.15.206
    - host: 192.168.15.209
    - host: 192.168.15.213

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

amcrest:
  - host: 192.168.15.190
    name: Garage
    username: admin
    password: !secret armcrest_password
    resolution: high
    stream_source: rtsp
    sensors:
      - motion_detector
  - host: 192.168.15.208
    name: Playroom
    username: admin
    password: !secret armcrest_password
    resolution: high
    stream_source: rtsp
    sensors:
      - motion_detector

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

camera:
  - platform: generic
    name: Weather Radar
    still_image_url: !secret weather_radar_url

automation:
  - alias: Notify David if garage is opened
    trigger:
      platform: state
      entity_id: cover.garage_door
      from: 'closed'
      to: 'open'
      for:
        hours: 0
        minutes: 0
        seconds: 45
    condition:
      condition: state
      entity_id: group.family
      state: 'not_home'
    action:
      - service: notify.halladay_bot
        data:
          message: The garage has been opened with nobody home.
  - alias: Notify David if garage is left open
    trigger:
      platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
    condition:
      condition: state
      entity_id: cover.garage_door
      state: 'open'
    action:
      - service: notify.halladay_bot
        data:
          message: 'The garage has been left open!'
  - alias: Toggle Office Sign On for Meeting
    trigger:
      platform: state
      entity_id: sensor.david_meeting_status
      from: 'Free'
      to: 'In Meeting'
    action:
      - service: switch.turn_on
        entity_id: switch.office_sign
  - alias: Toggle Office Sign Off for Free
    trigger:
      platform: state
      entity_id: sensor.david_meeting_status
      from: 'In Meeting'
      to: 'Free'
    action:
      - service: switch.turn_off
        entity_id: switch.office_sign
  - alias: Launch Alerts
    trigger:
      - platform: template
        value_template: '{{ (now().strftime("%s") | int + 600) == (states.sensor.spacex.state | int) }}'
    action:
      - service: notify.halladay_bot
        data:
          message: 'SpaceX launch in 10 minutes!'
  - alias: Front Lights On
    trigger:
      platform: sun
      event: sunset
    action:
      service: switch.turn_on
      entity_id: switch.front_door_light
  - alias: Front Lights Off
    trigger:
      platform: sun
      event: sunrise
    action:
      service: switch.turn_off
      entity_id: switch.front_door_light

group: !include groups.yaml
