homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 28
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret hass_api_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# History logging with InfluxDB
influxdb:

device_tracker:
  - platform: owntracks
  - platform: netgear
    host: !secret netgear_host
    username: !secret netgear_user
    password: !secret netgear_password
    port: !secret netgear_port
    interval_seconds: 30
    consider_home: 240
    track_new_devices: no

# Zones
zone:
  name: Church
  latitude: !secret church_latitude
  longitude: !secret church_longitude
  radius: 200
  icon: mdi:church

zone 2:
  name: !secret elem_name
  latitude: !secret elem_latitude
  longitude: !secret elem_longitude
  radius: 250
  icon: mdi:school

zone 3:
  name: !secret mschool_name
  latitude: !secret mschool_latitude
  longitude: !secret mschool_longitude
  radius: 250
  icon: mdi:school

zone 4:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 200
  icon: mdi:home

zone 5:
  name: Group
  latitude: !secret group_latitude
  longitude: !secret group_longitude
  radius: 200
  icon: mdi:group

zone 6:
  name: !secret gym_name
  latitude: !secret gym_latitude
  longitude: !secret gym_longitude
  radius: 300
  icon: mdi:dumbbell

ifttt:
  key: !secret ifttt_key

binary_sensor:
  - platform: command_line
    command: curl http://192.168.15.100:8888/api/cal
    name: David Meeting
    device_class: occupancy
    payload_on: True
    payload_off: False

sensor:
  - platform: darksky
    api_key: !secret dark_sky_key
    monitored_conditions:
      - summary
      - temperature
      - temperature_max
      - temperature_min
      - apparent_temperature
      - wind_speed
      - humidity
      - cloud_cover
      - precip_probability
  - platform: pi_hole
    host: 192.168.15.202
    monitored_conditions:
      - ads_percentage_today
      - dns_queries_today
  - platform: template
    sensors:
      garage_door_status:
        value_template: '{{ states.cover.door_control.state }}'
        friendly_name: 'Door Status'
      david_meeting_status:
        value_template: '{% if is_state("binary_sensor.david_meeting", "on") %}In Meeting{% else %}Free{% endif %}'
        friendly_name: David Status
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: since_last_boot
  - platform: usps
    username: !secret usps_username
    password: !secret usps_password
    name: usps_package

# Test Garage control
cover:
- platform: command_line
  covers:
    garage_door:
      command_open: curl --data '' 192.168.15.100:8888/api
      command_close: curl --data '' 192.168.15.100:8888/api
      command_stop: curl --data '' 192.168.15.100:8888/api
      command_state: curl 192.168.15.100:8888/api
      friendly_name: Door Control

notify:
 - name: halladay_bot
   platform: telegram
   api_key: !secret telegram_key
   chat_id: !secret telegram_chat_id

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password

automation:
  alias: Notify David if garage is open for one hour
  trigger:
    platform: state
    entity_id: cover.door_control
    from: 'closed'
    to: 'open'
    for:
      hours: 1
      minutes: 0
      seconds: 0
  action:
    - service: notify.halladay_bot
      data:
        message: The garage has been open for one hour!

camera:
  name: David
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.david_david_phone.attributes.latitude }},{{ states.device_tracker.david_david_phone.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:D%7C{{ states.device_tracker.david_david_phone.attributes.latitude }},{{ states.device_tracker.david_david_phone.attributes.longitude }}
  limit_refetch_to_url_change: true

group: !include groups.yaml
